endpoint: https://thespacedevs-production.up.railway.app/
transport:
  type: stdio
operations:
  source: manifest
  path: <test-dir>/apollo.json
schema:
  source: local
  path: <test-dir>/api.graphql
overrides:
  mutation_mode: all
introspection:
  execute:
    enabled: true
  introspect:
    enabled: true
  search:
    enabled: true
  validate:
    enabled: true
